language: julia
os:
  - linux
  - windows
  
julia:
  - 1.0
  - 1.4
  
notifications:
  email: 
    - elias@bouacida.fr



after_success:
- julia -e 'cd(Pkg.dir("RevealedPreferences")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'