language: julia
os:
  - linux
  - windows
  
julia:
  - 1.0
  - 1.4
  
notifications:
  email: false

codecov: true

after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'